In [1]:
!pip install transformers


In [2]:
!pip install datasets

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 521.2/521.2 kB 6.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 115.3/115.3 kB 11.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 134.8/134.8 kB 11.7 MB/s eta 0:00:00


In [3]:
from transformers import TFAutoModel , AutoTokenizer
import pandas as pd
from datasets import Dataset , DatasetDict

In [4]:
# Load your CSV file into a Pandas DataFrame
df = pd.read_csv("resume_job.csv")

# Assuming your CSV has columns 'CV Text', 'Job Description', and 'Label'
columns = ['CV Text', 'Job Description', 'Label']

# Create a Hugging Face Dataset
hf_dataset = Dataset.from_pandas(df[columns])

# Split the dataset into train, test, and validation
splits = hf_dataset.train_test_split(test_size=0.2)
dataset_dict = DatasetDict({
    'train': splits['train'],
    'test': splits['test'],
    'validation': splits['test']  # You can adjust this based on your needs
})

## this bloc will turn the csv file into a the hugging's face dataset dict format to work with it

In [5]:
model = TFAutoModel.from_pretrained("bert-base-uncased")
tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

Some weights of the PyTorch model were not used when initializing the TF 2.0 model TFBertModel: ['cls.predictions.transform.dense.bias', 'cls.predictions.bias', 'cls.predictions.transform.LayerNorm.bias', 'cls.seq_relationship.weight', 'cls.predictions.transform.LayerNorm.weight', 'cls.seq_relationship.bias', 'cls.predictions.transform.dense.weight']
- This IS expected if you are initializing TFBertModel from a PyTorch model trained on another task or with another architecture (e.g. initializing a TFBertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFBertModel from a PyTorch model that you expect to be exactly identical (e.g. initializing a TFBertForSequenceClassification model from a BertForSequenceClassification model).
All the weights of TFBertModel were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertModel for predictions w

tokenizer_config.json:   0%|          | 0.00/28.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

In [ ]:
input = tokenizer("i'am a good developer" , padding=True , truncation=True, return_tensors='tf')
input

{'input_ids': <tf.Tensor: shape=(1, 8), dtype=int32, numpy=array([[ 101, 1045, 1005, 2572, 1037, 2204, 9722,  102]], dtype=int32)>, 'token_type_ids': <tf.Tensor: shape=(1, 8), dtype=int32, numpy=array([[0, 0, 0, 0, 0, 0, 0, 0]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(1, 8), dtype=int32, numpy=array([[1, 1, 1, 1, 1, 1, 1, 1]], dtype=int32)>}

In [ ]:
output = model(input)
output

TFBaseModelOutputWithPoolingAndCrossAttentions(last_hidden_state=<tf.Tensor: shape=(1, 8, 768), dtype=float32, numpy=
array([[[ 0.07349944,  0.47614014,  0.08145045, ..., -0.15259919,
          0.24628453,  0.21631332],
        [ 0.40684196, -0.17027038,  0.2224595 , ..., -0.663429  ,
          0.69067127,  0.23974618],
        [ 0.5615704 , -0.13957886,  0.9411651 , ..., -0.4361333 ,
          0.30445912, -1.0131931 ],
        ...,
        [-0.01782769,  0.38533524,  0.7391065 , ..., -0.628267  ,
          0.02969595, -0.90244865],
        [ 0.29193276,  0.08606262, -0.376787  , ..., -0.01208934,
          0.16894129, -1.0393331 ],
        [ 0.8305764 ,  0.2564611 , -0.19565359, ...,  0.16396622,
         -0.6592187 , -0.12603647]]], dtype=float32)>, pooler_output=<tf.Tensor: shape=(1, 768), dtype=float32, numpy=
array([[-7.36293852e-01, -3.34754765e-01, -5.33152521e-01,
         5.83591640e-01,  4.63698626e-01, -1.88763607e-02,
         7.25151122e-01,  1.49340048e-01, -2.35704616e-0

In [6]:
dataset_dict

DatasetDict({
    train: Dataset({
        features: ['CV Text', 'Job Description', 'Label'],
        num_rows: 40
    })
    test: Dataset({
        features: ['CV Text', 'Job Description', 'Label'],
        num_rows: 11
    })
    validation: Dataset({
        features: ['CV Text', 'Job Description', 'Label'],
        num_rows: 11
    })
})

In [7]:
def tokenize(batch):
    return tokenizer(batch["CV Text"], padding=True, truncation=True)

In [8]:
dataset_encoded = dataset_dict.map(tokenize, batched=True, batch_size=None)

Map:   0%|          | 0/40 [00:00<?, ? examples/s]

Map:   0%|          | 0/11 [00:00<?, ? examples/s]

Map:   0%|          | 0/11 [00:00<?, ? examples/s]

In [9]:
import tensorflow as tf


In [10]:
dataset_encoded

DatasetDict({
    train: Dataset({
        features: ['CV Text', 'Job Description', 'Label', 'input_ids', 'token_type_ids', 'attention_mask'],
        num_rows: 40
    })
    test: Dataset({
        features: ['CV Text', 'Job Description', 'Label', 'input_ids', 'token_type_ids', 'attention_mask'],
        num_rows: 11
    })
    validation: Dataset({
        features: ['CV Text', 'Job Description', 'Label', 'input_ids', 'token_type_ids', 'attention_mask'],
        num_rows: 11
    })
})

In [34]:
# setting 'input_ids', 'attention_mask', 'token_type_ids', and 'label'
# to the tensorflow format. Now if you access this dataset you will get these
# columns in `tf.Tensor` format

dataset_encoded.set_format('tf',
                            columns=['input_ids', 'attention_mask', 'token_type_ids', 'Label'])

# setting BATCH_SIZE to 64.
BATCH_SIZE = 12

def order(inp):
    '''
    This function will group all the inputs of BERT
    into a single dictionary and then output it with
    labels.
    '''
    data = list(inp.values())
    return {
        'input_ids': data[1],
        'attention_mask': data[2],
        'token_type_ids': data[3]
    }, data[0]


# converting train split of `emotions_encoded` to tensorflow format
train_dataset = tf.data.Dataset.from_tensor_slices(dataset_encoded['train'][:])
# set batch_size and shuffle
train_dataset = train_dataset.batch(BATCH_SIZE).shuffle(1000)
# map the `order` function
train_dataset = train_dataset.map(order, num_parallel_calls=tf.data.AUTOTUNE)

# ... doing the same for test set ...
test_dataset = tf.data.Dataset.from_tensor_slices(dataset_encoded['test'][:])
test_dataset = test_dataset.batch(BATCH_SIZE)
test_dataset = test_dataset.map(order, num_parallel_calls=tf.data.AUTOTUNE)

In [18]:
inp, out = next(iter(train_dataset)) # a batch from train_dataset
print(inp, '\n\n', out)


{'input_ids': <tf.Tensor: shape=(12, 66), dtype=int64, numpy=
array([[  101,  1045,  2572,  1037, 10571,  3831,  3353,  2007,  3325,
         1999,  6605,  2436,  3136,  1010, 19940, 14651,  1010,  1998,
         8304, 11061,  1012,  1045,  2572, 27029,  1999,  7513,  2436,
         5097,  1998,  2031,  1037,  2844,  3086,  2000,  6987,  1012,
         1045,  2572,  3201,  2000,  9002,  2026,  3831,  4813,  2000,
         1037,  2136,  1999,  2342,  1997, 13296,  2490,  1012,   102,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0],
       [  101,  2007,  3325,  1999,  1037,  2655,  2415,  4044,  1010,
         1045,  2031, 10189,  2098,  2026,  8013,  2490,  4813,  2083,
         8304, 27050,  1998, 29304,  3314,  1012,  1045,  2572, 26398,
         2012,  4346,  6581,  2326,  1998, 12725,  8013,  9967,  1012,
         1045,  2572,  7568,  2055,  1996,  4495,  2000,  3288,  2026,
         8013,  2490, 11532,  2000,  1037,  2535,  1999,

In [35]:
class BERTForClassification(tf.keras.Model):

    def __init__(self, bert_model, num_classes):
        super().__init__()
        self.bert = bert_model
        self.fc = tf.keras.layers.Dense(num_classes, activation='softmax')

    def call(self, inputs):
        x = self.bert(inputs)[1]
        return self.fc(x)

In [36]:
classifier = BERTForClassification(model, num_classes=2)

classifier.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=1e-5),
    loss=tf.keras.losses.SparseCategoricalCrossentropy(),
    metrics=['accuracy']
)

In [37]:
history = classifier.fit(
    train_dataset,
    epochs=3
)

Epoch 1/3
4/4 [==============================] - 70s 8s/step - loss: 0.7765 - accuracy: 0.3500
Epoch 2/3
4/4 [==============================] - 34s 8s/step - loss: 0.6295 - accuracy: 0.6500
Epoch 3/3
4/4 [==============================] - 34s 8s/step - loss: 0.5521 - accuracy: 0.8750


In [38]:
classifier.evaluate(test_dataset)

1/1 [==============================] - 8s 8s/step - loss: 0.6389 - accuracy: 0.6364


[0.6389472484588623, 0.6363636255264282]